name: fastcan-rtd
channels:
  - conda-forge
dependencies:
  - micromamba
  - pip
  - pydata-sphinx-theme
  - sphinx-gallery
  - sphinx-design
  - sphinxcontrib-plantuml
  - jupyterlite-sphinx
  - plantuml
  - matplotlib
  - pandas
  - pip:
      - .
      - jupyterlite-xeus