name: xeus-kernels
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - matplotlib
  - pandas
  - fastcan
  - pip:
    - pyodide-http