# Authors: The fastcan developers
# SPDX-License-Identifier: MIT

import numpy as np
import numpy.typing as npt

def _predict(
    X: npt.NDArray[np.float64],
    y_ref: npt.NDArray[np.float64],
    coef: npt.NDArray[np.float64],
    intercept: npt.NDArray[np.float64],
    feat_ids: npt.NDArray[np.intc],
    delay_ids: npt.NDArray[np.intc],
    output_ids: npt.NDArray[np.intc],
    session_sizes_cumsum: npt.NDArray[np.intc],
    max_delay: int,
    y_hat: npt.NDArray[np.float64],
) -> None: ...
def _compute_term_lib(
    X: npt.NDArray[np.float64],
    y_hat: npt.NDArray[np.float64],
    max_delay: int,
    session_sizes_cumsum: npt.NDArray[np.intc],
    unique_feat_ids: npt.NDArray[np.intc],
    unique_delay_ids: npt.NDArray[np.intc],
    term_lib: npt.NDArray[np.float64],
) -> None: ...
def _compute_dydx(
    X: npt.NDArray[np.float64],
    y_hat: npt.NDArray[np.float64],
    max_delay: int,
    session_sizes_cumsum: npt.NDArray[np.intc],
    y_ids: npt.NDArray[np.intc],
    coefs: npt.NDArray[np.float64],
    unique_feat_ids: npt.NDArray[np.intc],
    unique_delay_ids: npt.NDArray[np.intc],
    const_term_ids: npt.NDArray[np.intc],
    jac_yyd_ids: npt.NDArray[np.intc],
    jac_coef_ids: npt.NDArray[np.intc],
    jac_term_ids: npt.NDArray[np.intc],
    term_lib: npt.NDArray[np.float64],
    jc: npt.NDArray[np.float64],
    dydx: npt.NDArray[np.float64],
) -> None: ...
def _compute_d2ydx2(
    X: npt.NDArray[np.float64],
    y_hat: npt.NDArray[np.float64],
    max_delay: int,
    session_sizes_cumsum: npt.NDArray[np.intc],
    y_ids: npt.NDArray[np.intc],
    coefs: npt.NDArray[np.float64],
    unique_feat_ids: npt.NDArray[np.intc],
    unique_delay_ids: npt.NDArray[np.intc],
    const_term_ids: npt.NDArray[np.intc],
    jac_yyd_ids: npt.NDArray[np.intc],
    jac_coef_ids: npt.NDArray[np.intc],
    jac_term_ids: npt.NDArray[np.intc],
    hess_yyd_ids: npt.NDArray[np.intc],
    hess_coef_ids: npt.NDArray[np.intc],
    hess_term_ids: npt.NDArray[np.intc],
    hess_yd_ids: npt.NDArray[np.intc],
    term_lib: npt.NDArray[np.float64],
    dydx: npt.NDArray[np.float64],
    jc: npt.NDArray[np.float64],
    hc: npt.NDArray[np.float64],
    d2ydx2: npt.NDArray[np.float64],
) -> None: ...
def _compute_d2ydx2p(
    X: npt.NDArray[np.float64],
    y_hat: npt.NDArray[np.float64],
    max_delay: int,
    session_sizes_cumsum: npt.NDArray[np.intc],
    y_ids: npt.NDArray[np.intc],
    coefs: npt.NDArray[np.float64],
    unique_feat_ids: npt.NDArray[np.intc],
    unique_delay_ids: npt.NDArray[np.intc],
    const_term_ids: npt.NDArray[np.intc],
    jac_yyd_ids: npt.NDArray[np.intc],
    jac_coef_ids: npt.NDArray[np.intc],
    jac_term_ids: npt.NDArray[np.intc],
    hess_yyd_ids: npt.NDArray[np.intc],
    hess_coef_ids: npt.NDArray[np.intc],
    hess_term_ids: npt.NDArray[np.intc],
    hess_yd_ids: npt.NDArray[np.intc],
    term_lib: npt.NDArray[np.float64],
    dydx: npt.NDArray[np.float64],
    p: npt.NDArray[np.float64],
    jc: npt.NDArray[np.float64],
    hc: npt.NDArray[np.float64],
    d2ydx2: npt.NDArray[np.float64],
    d2ydx2p: npt.NDArray[np.float64],
) -> None: ...
