"""
Lazy FastCan selector.
"""

# Authors: The fastcan developers
# SPDX-License-Identifier: MIT

from numbers import Integral, Real

import numpy as np
from scipy.linalg import orth
from sklearn.base import BaseEstimator
from sklearn.utils._param_validation import Interval

from ._fastcan import _check_indices_params, _check_X_y


def _classical_gram_schmidt(x, W):
    """Classical Gram-Schmidt orthogonalization.
    Parameters
    ----------
    x: (n_samples,) Features for orthogonalization.
    W: (n_samples, n_selected) Selected orthonormal features,
        where n_selected can be zero.

    Returns
    -------
    q: (n_samples,) Orthonormal features.
    """
    q = x - W @ (W.T @ x)
    norm = np.linalg.norm(q)
    if norm == 0:
        norm = 1.0
    return q / norm


def _default_feature_generator(X, skip_indices):
    """Default feature generator that yields each column of X as a feature."""
    n_features = X.shape[1]
    skip_indices = _check_indices_params(skip_indices, n_features)
    skip_set = set(skip_indices.tolist())
    for j in range(n_features):
        if j in skip_set:
            continue
        yield j, X[:, j]


def _check_generated_features(idx, feature, n_samples):
    """Check the validity of generated features."""
    if not isinstance(idx, Integral):
        raise TypeError(f"Generated feature index {idx} is not an integer.")
    if idx < 0:
        raise ValueError(f"Generated feature index {idx} is negative.")
    if feature.ndim != 1:
        raise ValueError(f"Generated feature with index {idx} is not one-dimensional.")
    if feature.shape[0] != n_samples:
        raise ValueError(
            f"Generated feature with index {idx} has length {feature.shape[0]}, "
            f"but expected length is {n_samples}."
        )
    if not np.isfinite(feature).all():
        raise ValueError(
            f"Generated feature with index {idx} contains non-finite values."
        )


class LazyFastCan(BaseEstimator):
    """Lazy version of FastCan selector.

    .. versionadded:: 0.5.1

    Parameters
    ----------
    n_features_to_select : int, default=1
        The parameter is the absolute number of features to select.

    feature_generator : callable or None, default=None
        A generator that takes the input data `X` and an array of `skip_indices`
        and yields `(index, feature)` tuples,
        where `index` should be from 0 to n_features-1.
        The `skip_indices` indicates which features should be skipped.
        If the generator requires additional parameters,
        you can use `functools.partial` to wrap the generator with those parameters.

    n_init : int, default=0
        The number of initial samples to skip before starting feature selection.
        This can be useful for features generated by time shifting.

    tol : float, default=1e-10
        Tolerance for linear dependence check.
        The classical Gram-Schmidt fails when abs(x.T @ W) > `tol`.

    Attributes
    ----------
    indices_ : ndarray of shape (n_features_to_select,), dtype=int
        The indices of the selected features. The order of the indices
        is corresponding to the feature selection process.

    support_ : ndarray of shape (n_features,), dtype=bool
        The mask of selected features.

    scores_ : ndarray of shape (n_features_to_select,), dtype=float
        The h-correlation scores of selected features. The order of
        the scores is corresponding to the feature selection process.


    Examples
    --------
    >>> from functools import partial
    >>> from fastcan import LazyFastCan
    >>> from fastcan.narx import gen_time_shift_features, make_time_shift_ids
    >>> fg = partial(gen_time_shift_features, ids=make_time_shift_ids(2, 2))
    >>> X = [[1, 2], [3, 4], [5, 6], [7, 8]]
    >>> y = [[0, 0], [0, 1], [1, 1], [0, 2]]
    >>> LazyFastCan(2, feature_generator=fg).fit(X, y).indices_
    array([2, 1])
    """

    _parameter_constraints: dict = {
        "n_features_to_select": [
            Interval(Integral, 1, None, closed="left"),
        ],
        "feature_generator": [callable, None],
        "n_init": [Interval(Integral, 0, None, closed="left")],
        "tol": [Interval(Real, 0, None, closed="neither")],
    }

    def __init__(
        self,
        n_features_to_select=1,
        feature_generator=None,
        n_init=0,
        tol=1e-10,
    ):
        self.n_features_to_select = n_features_to_select
        self.feature_generator = feature_generator
        self.n_init = n_init
        self.tol = tol

    def fit(self, X, y):
        self._validate_params()
        X, y = _check_X_y(self, X, y, order="C")
        feature_generator = self.feature_generator or _default_feature_generator

        n_samples = X.shape[0]

        y_transformed = orth(y[self.n_init :] - y[self.n_init :].mean(0))
        W = np.zeros((n_samples - self.n_init, self.n_features_to_select))
        indices = np.zeros(self.n_features_to_select, dtype=int)
        scores = np.zeros(self.n_features_to_select, dtype=float)

        max_feat_idx = -1

        for i in range(self.n_features_to_select):
            best_score = -np.inf
            best_index = -1
            best_feat = None
            for j, feat in feature_generator(X, skip_indices=indices[:i]):
                _check_generated_features(j, feat, n_samples)
                feat = feat[self.n_init :]
                max_feat_idx = max(max_feat_idx, j)
                feat_centered = feat - feat.mean()
                feat_orth = _classical_gram_schmidt(feat_centered, W[:, :i])
                # Linear dependence check
                g = feat_orth.T @ W[:, :i]
                if np.any(np.abs(g) > self.tol):
                    continue
                r = feat_orth.T @ y_transformed
                score = r @ r
                if score > best_score:
                    best_score = score
                    best_index = j
                    best_feat = feat_orth
            if best_index == -1:
                raise RuntimeError(
                    "No more features can be selected when adding "
                    f"the {i + 1}th feature."
                )
            if best_score == 0:
                raise RuntimeError(
                    f"No improvement can be achieved when adding the {i + 1}th feature."
                )
            indices[i] = best_index
            scores[i] = best_score
            W[:, i] = best_feat
        self.indices_ = indices
        self.scores_ = scores
        self.n_features_ = max_feat_idx + 1
        return self
