name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          environments: default
          cache: true

      - name: Re-install local
        run: |
          pixi reinstall --frozen fastcan

      - name: Lint with ruff
        run: |
          pixi run lint
      - name: Lint with cython-lint
        run: |
          pixi run cython-lint
      - name: Format with black
        run: |
          pixi run fmt
      - name: Type check with mypy
        run: |
          pixi run type
      - name: Test coverage
        shell: bash
        run: |
          FMT=xml pixi run test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build SDist
        run: |
          pixi run build-sdist
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
