# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: default

    - name: Lint with ruff
      run: |
        pixi run lint
    - name: Test with pytest
      run: |
        pixi run test
    - name: Test with doctest
      shell: bash
      run: |
        CMD=doctest pixi run doc


  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    runs-on: ${{ matrix.os }}
    needs: test

    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: default

    - name: Build package
      run: |
        pixi run cibuildwheel
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-${{ strategy.job-index }}
        path: dist/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
