# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  release:
    types: [published]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          # Window 64 bit
          - os: windows-latest
            python: "3.10"
            platform_id: win_amd64
          - os: windows-latest
            python: "3.11"
            platform_id: win_amd64
          - os: windows-latest
            python: "3.12"
            platform_id: win_amd64

          # Linux 64 bit manylinux2014
          - os: ubuntu-latest
            python: "3.10"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: "3.11"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: "3.12"
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # MacOS x86_64
          - os: macos-12
            python: "3.10"
            platform_id: macosx_x86_64
          - os: macos-12
            python: "3.11"
            platform_id: macosx_x86_64
          - os: macos-12
            python: "3.12"
            platform_id: macosx_x86_64

          # MacOS arm64
          - os: macos-14
            python: "3.10"
            platform_id: macosx_arm64
          - os: macos-14
            python: "3.11"
            platform_id: macosx_arm64
          - os: macos-14
            python: "3.12"
            platform_id: macosx_arm64
    runs-on: ${{ matrix.os }}

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        cargo install --locked --git https://github.com/prefix-dev/pixi.git
        pixi install -a
    - name: Lint with ruff
      run: |
        pixi run lint
    - name: Test with pytest
      run: |
        pixi run test
    - name: Test with doctest
      shell: bash
      run: |
        CMD=doctest pixi run doc
    - name: Build package
      run: |
        pixi run build-wheel
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}-${{ strategy.job-index }}
        path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
